version: '3.9'

services:
  tmdatabase:
    image: postgres
    environment:
      POSTGRES_DB: "Task-manager-db"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpassword"
    ports:
      - "5434:5432"
    volumes:
      - pg-data:/var/lib/postgresql/realdata

  testtmdatabase:
    image: postgres
    environment:
      POSTGRES_DB: "Test-task-manager-db"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpassword"
    ports:
      - "5435:5432"
    volumes:
      - pg-data:/var/lib/postgresql/testdata

volumes:
  pg-data:
    driver: local
